core/ciao_adapter.js
core/helpers/flavorDetails.js
core/tenantService.js
routes/data.js

onSuccess and onError methods added to ciao_adapter's prototype.
Implementation returns new adapter object with added callbacks.
Signed-off-by: Jorge A Villalobos <jorge.villalobos.gutierrez@intel.com>

Add callback methods to ciaoAdapter

---

core/ciao_adapter.js
core/helpers/flavorDetails.js
core/nodeService.js
core/tenantService.js

Includes progress on #26 new feature.
Improves stability on admin page (issue) #24 
Grouped instances component should be visible now(tested on clearlinux and ubuntu) Fixes #9

Added fixes, and validation to prevent crashes.

---

js/components/instancesCounter.js
js/components/instancesHost.js
js/components/instancesTenant.js
js/components/nodeSummary.js
js/components/nodes.js
js/components/usageSummary.js

Implement check via "updating" status on visual components in order to
avoid request overload on the backend of the application. This greatly
improves application performance. Improvement on issue #35.
Signed-off-by: Jorge A Villalobos <jorge.villalobos.gutierrez@intel.com>

Reduce request overload

---

js/components/usageSummary.js

Remove unintended comment and replace map function with forEach. In
addition use proper naming for variable.
Signed-off-by: Jorge A Villalobos <jorge.villalobos.gutierrez@intel.com>

Use proper function and naming

---

css/css_framework/framework.css
install.sh
js/components/addInstances.js
js/util/validations.js

Number of instances input text validated
Warning message added

Issue28 - Tenant - Input validation on Add Instances functionality

---

js/components/catalogue/customCatalogue.js
js/components/catalogue/customTable.js

Removed a code of line where the id was deleted causing the wrong selection.

issue #10 Fix selection of one Node/Instance 

---

css/css_framework/framework.css

- Padding left and right changed to have workspace wider
- This fix the issue #13  

Horizontal scroll bar on tables, fixed

---

css/css_framework/framework.css
js/components/catalogue/tableActionToolbar.js

- CSS style applied to table action toolbar
- CSS spyle applied to pagination component
- This fix the issue #1 

Buttons not grabbing the right color schema fix

---

js/components/catalogue/customCatalogue.js
js/components/catalogue/customTable.js
js/components/instancesHost.js
js/components/network_cnci.js
js/components/nodes.js

Fix the error selecting one instance by Adding an ID field to the catalogue component to specify which field should consider as the ID
Issue #50

Fix the error selecting one instance

---

core/tenantService.js
js/components/instancesHost.js

Change the code to work with the state "active" in instances table
issue: #57

Add state active in instances

---

css/css_framework/framework.css
install.sh

- Set style on header tables
- Changes on install.sh file: set proper paths to jquery and css files
- This fix the issue #61 

Table headers are being displayed without the proper style, fix

---

js/components/catalogue/customModal.js
js/components/instancesHost.js

- Adding modal when select all remove instances
- Adding modal when select all start instances
- Adding modal when select all stop instances
- This fix #49 

Remove all instances with no confirmation modal, fix

---

core/nodeService.js
core/session.js
core/tenantService.js
routes/authenticate.js

This fix is specifically for handling errors in the following case:
- UI is deployed normally and keystone is reachable at this time.
- Keystone becomes unavailable (shutdown, network, etc)
Fixes #51
Signed-off-by: Jorge Villalobos <jorge.villalobos.gutierrez@intel.com>

Prevent crash when keystone becomes unreachable

---

css/css_framework/framework.css
js/components/login.js

- Proper alert messages set
- This fix solve the issue #32 

Handling UI login when Keystone is not reachable

---

js/components/groupOverview.js

Use active tenant's id properly in order to render component with
corresponding information.
Fixes #60
Signed-off-by: Jorge Villalobos <jorge.villalobos.gutierrez@intel.com>

Update group instanced with multiple tenants

---

js/components/nodeSummary.js
js/components/nodeSummaryChart.js
js/d3_components/d3DonutChartSummary.js

- D3 Donut chart component created
- Node summary chart added to admin view
- This fix the issue #71 

Admin - Nodes summary donut chart missing, fix

---

js/components/catalogue/customCatalogue.js
js/components/catalogue/tableActionToolbar.js
js/components/instancesHost.js
js/components/instancesTenant.js
js/components/network_cnci.js
js/components/nodeSummary.js
js/components/nodeSummaryChart.js
js/components/nodes.js
js/d3_components/d3DonutChartSummary.js

- Validated the placeholder attribute for toolbar search element
- Deleted console messages in node files
- This fix the issue #76 

Search Nodes/CNCIs input text with wrong placeholder attribute value - fix

---

core/tenantService.js

- Handled the endpoint response
- Error status 500 is send when the endpoint fails
- This fix the issue #23 

Flavors detail endpoint returns valid response with fake tenant id -fix

---

css/css_framework/framework.css
install.sh
js/components/underConstruction.js
js/components/usageSummary.js
js/pages/under_construction.js
package.json
routes/admin.js
routes/tenant.js
views/pages/under_construction.ejs

- View Usage History button added
- Under Construction page and it workflow added
- Usage Summary container width changed
- This fix the issue #81 

Missing View Usage History button - fix

---

js/components/login.js
routes/authenticate.js

- User Notification when bad/none user credentials given.
- User Notification when Keystone is not available.
- Fix for issue 90

Fixes User Notifications on login.

---

core/helpers/flavorDetails.js
css/css_framework/framework.css
js/components/instancesHost.js
js/components/instancesTenant.js
js/pages/tenant_group.js

- Instances table applies proper style for active status.
- Grouped instances component displays count number of running instances.
- Fix for issues #94 and #95.

Fixes issues in Grouped Instances component and Instance Table

---

js/components/login.js
routes/authenticate.js

Fixes user notifications on keystone connection refused.

---

core/ciao_adapter.js
core/session.js
css/css_framework/framework.css
deploy.sh
install.sh
js/components/addInstances.js
js/components/groupOverview.js
js/components/login.js
js/components/messages.js
js/components/nodeSummary.js
js/components/usageSummary.js
js/pages/admin.js
js/pages/login_page.js
js/pages/tenant_admin.js
js/util/logger.js
routes/authenticate.js
views/default_template.ejs

features:
- token renewal
- css styling
- show http errors on login and tenant pages

Alerts integration

---

core/blockService.js
core/ciao_adapter.js
core/session.js
css/css_framework/framework.css
deploy.sh
install.sh
js/components/addInstances.js
js/components/groupOverview.js
js/components/login.js
js/components/messages.js
js/components/nodeSummary.js
js/components/usageSummary.js
js/pages/admin.js
js/pages/login_page.js
js/pages/tenant_admin.js
js/util/logger.js
routes/authenticate.js
routes/data.js
tools/cli-debug.js
views/default_template.ejs

Start block storage integration.
- new core element in code: "blockService" which holds implementation to consume storage API
- cli-debug tool: used to test API impl
Implementation of the API data layer includes Create, Delete, and list volume functionality.
** Feature doesn't affect the visuals of the application, until visual elements are implemented.
**This feature is Backwards compatible

Block storage integration (data layer)

---

js/components/login.js
js/components/messages.js
routes/authenticate.js

- Removes duplicated message on keystone connection errors.
- Fixes #108
- Fixes #109

Fixes alert messages on keystone connection errors to be user friendly

---

Makefile

- Copy files from vendor seccessfully
- Babel does not crash anymore
- Fixes #116

Fix for Makefile when install-dev is executed.

---

js/pages/admin.js

Fixes Logger object not being created on Admin Overview page.

---

css/d3_components/d3Framework.css
install.sh
js/components/lineChartDetail.js
js/components/usageSummary.js
js/d3_components/d3LineChartDetail.js
js/pages/tenant_usage_details.js
routes/data.js
routes/tenant.js
views/pages/tenant_usage.ejs

- Refactored codi for the entire functionality
- CPU usage history component added
- Disk usage history component added

Tenant Missing Usage History feature - Fix

---

Makefile
install.sh

- Fixes #132, install.sh includes temporal testing code
- Fixes #133, Makefile - install-dev does not build tenant-details
- Fixes #134, Makefile - clean does not remove build/javascripts/ files

Fixes for Makefile and removal of test code.

---

core/tenantService.js
css/css_framework/framework.css
js/components/catalogue/customAlert.js
js/components/catalogue/customCatalogue.js
js/components/catalogue/customTable.js
js/components/catalogue/tableActionToolbar.js
js/components/instancesHost.js
js/components/network_cnci.js
js/components/nodes.js
js/pages/admin.js

Fix issue-15  and issue-16 
Fix errors in the node catalogue component:
-Select one record of the table
This fix also includes the proposal of being able to select many records
using the expected behavior of the checkboxes instead of a radio.
-Select any option in the dropdown

Issue 16 15

---

js/components/instancesHost.js

Show dialog to confirm delete when a user attempts
to delete records from the instance table

Fix issue-146

---

css/css_framework/framework.css
install.sh
js/components/addInstances.js
js/components/elementSummary.js
js/components/usageSummary.js
routes/data.js
views/pages/tenant.ejs
views/pages/tenant_usage.ejs

- Added new styles to the css framework
- Component structure changed according wireframes
- Fixed stylesheets path in install.sh script
- This fix the issue #137 

Implement styling for usage summary component - done

---

css/css_framework/framework.css
install.sh
js/components/addInstances.js
js/components/elementSummary.js
js/components/instancesCounter.js
js/components/usageSummary.js
routes/data.js
views/pages/admin.ejs
views/pages/tenant.ejs
views/pages/tenant_usage.ejs

- New styles applied to usage summary component
- Structure changed according wireframes
- This fix issue #143
Signed-off-by: Teresita de Jesus Guerrero Vela teresita.guerrero.vela@intel.com

Admin view - Implement styling for usage summary component - Done

---

Makefile
js/components/catalogue/customAlert.js

- Fixes #148, Makefile - css content not properly copied to public path
- Fixes #149, Tenant - Rewording on custom alert for Instance selection

Fixes for custom alert on instance selection and Makefile

---

config/ciao_config.json
core/blockService.js
core/ciao_adapter.js
core/helpers/flavorDetails.js
routes/data.js
tools/cli-debug.js

This pull request delivers progress on enhancement #112 
Storage endpoint, port, and host can be specified in ciao_config.json
file.

Add config capability for setting storage

---

css/css_framework/framework.css
css/d3_components/d3Framework.css
js/components/lineChartDetail.js
js/d3_components/d3LineChartDetail.js
js/pages/tenant_usage_details.js
routes/data.js

- Range to get data set to 2 days (current date and 1 back)
- Styles applied to the chart line component
- New styles added to the CSS framework and d3 CSS file
- This fix the issue #136 and issue #138 

Change the line chart component range time - Done

---

core/tenantService.js
js/components/instancesHost.js
js/pages/machine.js

fix issues in machine page caused for the wrong id.

fix issue #155

---

js/pages/machine.js

Fix error in the machine page. to update the
information of the catalogue after a time

Fix issue 156

---

js/components/catalogue/catalogue.js

add catalogue component

---

core/blockService.js
core/tenantService.js
js/components/catalogue/catalogue.js
js/components/catalogue/customTable.js
js/pages/tenant_admin.js
routes/data.js
views/pages/tenant.ejs

Upon completion this pull request should close #112 
Storage implementations include the following:
* Implementation of block storage API endpoints that allow the following operations:
- create volume
- delete volume
- Attach volume
- retrieve list of volumes
* Implementation of Volume table in tenant page
- React js implementation in tenant page
Note: wireframe implementation is minimal, current storage integration targets functionality

Storage visual implementation 

---

js/components/catalogue/catalogue.js
js/components/catalogue/customModal.js
js/pages/tenant_admin.js

Implement modal to create Volumes.

Fix issue 173

---

core/tenantService.js
js/components/catalogue/customModal.js
js/pages/tenant_admin.js
routes/data.js

New additions,
visual create volume functionality fixed.

Storage visuals

---

js/components/catalogue/customModal.js
js/pages/tenant_admin.js

Introduced fixes and implementation on Delete volume feature.
Current implementation support triggering modal windows and selecting
values in order to perform requested features.
Fixes include:
correct dom management due to customModal show state.
correct parameter setting in modal fields
Closes #173 #174
Signed-off-by: Jorge Villalobos <jorge.villalobos.gutierrez@intel.com>

Fully functional Create/Delete/Attach feature

---

js/components/catalogue/catalogue.js
js/components/catalogue/customModal.js
js/components/instancesHost.js
js/pages/tenant_admin.js

Fixed typos, minor bugs, and add select functionality into volume
component based on catalogue.
Signed-off-by: Jorge Villalobos <jorge.villalobos.gutierrez@intel.com>

volumes:Fix typos, add select functionality

---

core/helpers/flavorDetails.js
css/css_framework/framework.css
js/components/elementSummary.js
js/components/groupOverview.js
js/components/instancesGroup.js
js/components/usageSummary.js
js/d3_components/d3ElementSummary.js
views/pages/tenant.ejs

- Added new look & feel to the grouped instances component
- This fix the issue #153 
**Important Note:** Merging this branch adds a JS warning that does not affect any functionality. this should be raised as a issue with low priority to be fixed in a separate PR. 

Tenant - Grouped instances new styles - Done

---

css/css_framework/framework.css
js/components/catalogue/customModal.js
js/pages/tenant_admin.js

Fix issue in the modal. After creating a Volume, If you try to create a new one the fields are pre-filled and they are unable to edit.

Issue modal

---

js/d3_components/d3ElementSummary.js

- A conditional function was added to print "0" when needed.
- This fix the issue #171 

Admin - Blank percentage when no running instances in Usage Summary -Fix

---

js/pages/tenant_admin.js

- Disabled logger from add instances component
- This fix the issue #124 

Tenant - Alert message displayed after launching instances -Fix

---

install.sh
js/components/navbar.js
js/pages/admin.js
js/pages/tenant_detail.js
package.json
routes/admin.js
views/pages/admin.ejs
views/pages/tenant_detail.ejs

- Modified navbar tenant links
- Added Tenant detail view
- Switch tenant functionality added
- This fix the issue #152 

Admin - Changing tenant fails to update the page

---

README.md
core/blockService.js
core/tenantService.js
js/pages/tenant_admin.js
routes/data.js

@arturonuman  please help check this feature.
In addition there are some bug fixes and text formatting.

Implement detach feature

---

js/components/catalogue/customModal.js
js/pages/tenant_admin.js

Add validation to 'size' field be a number greater than 0
Add label to specify that 'size' field is in GB

Issue 190 and 204

---

core/imageService.js
routes/data.js

Fixes #208, Implements read image(s) functionality (API)
Fixes #209, Implements delete image functionality (API)

Image: Read and delete images

---

core/imageService.js

Implements the following endpoint:
- Create image - POST /v2/images

Image: implement image creation functionality (API)

---

routes/tenant.js

- Set a variable to get the current tenant name and display it correctly
- This fixes the issue #197 

Tenant - Current tenant name display incorrectly - Fix

---

js/components/navbar.js
routes/tenant.js

- Navbar Tenant menu changed to redirect to the proper URL
- This fixes issue #198 

Tenant - Tenant URL switch to admin URL - Fix

---

js/components/navbar.js

- Added a switch to display this button properly.
- This fixes the issue #199 

Tenant - Back Overview button unexpected behaviour - Fix

---

core/tokenManager.js

This should fix issues #200 and #219.
I have tested these locally, need confirmation before merge.

Authentication: fix logic when scoping tokens

---

js/components/elementSummary.js
js/components/instancesCounter.js
js/components/usageSummary.js
js/pages/tenant_usage_details.js
routes/admin.js
routes/tenant.js

- Added url reference according user.
- Added new routes to track selected tenant for usage view.
- This fixes the issues #215 and #216 

Analytics pages are not reachable - fix

---

js/pages/machine.js
js/pages/tenant_detail.js
js/pages/tenant_usage_details.js
routes/admin.js
routes/tenant.js

- Added a flag to standardize label in admin pages
- This fixes issue #231 

Admin - Back to admin overview button text discrepances - fix

---

core/imageService.js
routes/data.js

- Fixes #243, Image Endpoints don't call image service methods

Fix Image Endpoints to call image service methods properly.

---

core/imageService.js
routes/data.js

Merges tipoc/image branch into development

Merging Image Service endpoints

---

core/imageService.js

Disclaimer for Image service component.

---

core/externalIPService.js
routes/data.js

- Create pool endpoint implemented in the backend side
- List pools endpoint implementes in the backend side
- List pool by id endpoint implemented in the backend side
- Delete pool endpoint implemented in the backend side
- Add ips to a pool endpoint implemented in the backend side
- This fixes issue #242 

Add External IP API support: pool management

---

core/externalIPService.js

- Misspelling variable changed
- This fixes issue #265

Get a Pool endpoint not retrieving any data

---

core/externalIPService.js
routes/data.js

- Delete Subnets
- Delete External IPs
- Unmap IPs
- This fixes the issue #264 

Implement missing endpoint for external IPs

---

core/tenantService.js

remove comments and logs which are not necessary.

Remove unnecessary log message
